if(OpenCMISS_WITH_C_BINDINGS OR OpenCMISS_WITH_Python_BINDINGS)
  if(DEFINED OpenCMISS_Python_VERSION)
    set(OpenCMISS_Python_VERSION "${OpenCMISS_Python_VERSION}" CACHE STRING "Python version number to use when building OpenCMISS libraries." FORCE)
  else()
    set(OpenCMISS_Python_VERSION "3.8" CACHE STRING "Python version number to use when building OpenCMISS libraries." FORCE)
  endif()
endif()
if(OpenCMISS_WITH_Python_BINDINGS)
  if(DEFINED OpenCMISS_SWIG_VERSION)
    set(OpenCMISS_SWIG_VERSION "${OpenCMISS_SWIG_VERSION}" CACHE STRING "SWIG version number to use when building OpenCMISS libraries." FORCE)
  else()
    set(OpenCMISS_SWIG_VERSION "4.0.0" CACHE STRING "SWIG version number to use when building OpenCMISS libraries." FORCE)
  endif()
endif()
if(OpenCMISS_WITH_MPI)
  if(DEFINED OpenCMISS_MPI_VERSION)
    set(OpenCMISS_MPI_VERSION "${OpenCMISS_MPI_VERSION}" CACHE STRING "External MPI library version number to use when building OpenCMISS libraries." FORCE)
  else()
    set(OpenCMISS_MPI_VERSION "3.0" CACHE STRING "External MPI library version number to use when building OpenCMISS libraries." FORCE)
  endif()
endif()
if(OpenCMISS_WITH_OpenMP)
  if(DEFINED OpenCMISS_OpenMP_VERSION)
    set(OpenCMISS_OpenMP_VERSION "${OpenCMISS_OpenMP_VERSION}" CACHE STRING "External OpenMP version number to use when building OpenCMISS libraries." FORCE)
  else()
    set(OpenCMISS_OpenMP_VERSION "4.0" CACHE STRING "External OpenMP version number to use when building OpenCMISS libraries." FORCE)
  endif()
endif()
if(OpenCMISS_WITH_CUDA)
  if(DEFINED OpenCMISS_CUDA_VERSION)
    set(OpenCMISS_CUDA_VERSION "${OpenCMISS_CUDA_VERSION}" CACHE STRING "External CUDA version number to use when building OpenCMISS libraries." FORCE)
  else()
    set(OpenCMISS_CUDA_VERSION "12.4" CACHE STRING "External CUDA version number to use when building OpenCMISS libraries." FORCE)
  endif()
endif()
if(OpenCMISS_WITH_CellML)
  if(DEFINED OpenCMISS_CellML_VERSION)
    set(OpenCMISS_CellML_VERSION "${OpenCMISS_CellML_VERSION}" CACHE STRING "External CellML library version number to use when building OpenCMISS libraries." FORCE)
  else()
    set(OpenCMISS_CellML_VERSION "0.5.0" CACHE STRING "External CellML library version number to use when building OpenCMISS libraries." FORCE)
  endif()
endif()
if(OpenCMISS_WITH_FieldML)
  if(DEFINED OpenCMISS_FieldML_VERSION)
    set(OpenCMISS_FieldML_VERSION "${OpenCMISS_FieldML_VERSION}" CACHE STRING "External FieldML library version number to use when building OpenCMISS libraries." FORCE)
  else()
    set(OpenCMISS_FieldML_VERSION "0.5.0" CACHE STRING "External FieldML library version number to use when building OpenCMISS libraries." FORCE)
  endif()
endif()
if(OpenCMISS_WITH_HYPRE)
  if(DEFINED OpenCMISS_HYPRE_VERSION)
    set(OpenCMISS_HYPRE_VERSION "${OpenCMISS_HYPRE_VERSION}" CACHE STRING "External HYPRE library version number to use when building OpenCMISS libraries." FORCE)
  else()
    set(OpenCMISS_HYPRE_VERSION "2.23.0" CACHE STRING "External HYPRE library version number to use when building OpenCMISS libraries." FORCE)
  endif()
endif()
if(OpenCMISS_WITH_MUMPS)
  if(DEFINED OpenCMISS_MUMPS_VERSION)
    set(OpenCMISS_MUMPS_VERSION "${OpenCMISS_MUMPS_VERSION}" CACHE STRING "External MUMPS library version number to use when building OpenCMISS libraries." FORCE)
  else()
    set(OpenCMISS_MUMPS_VERSION "5.7.3" CACHE STRING "External MUMPS library version number to use when building OpenCMISS libraries." FORCE)
  endif()
endif()
if(OpenCMISS_WITH_ParMETIS)
  if(DEFINED OpenCMISS_ParMETIS_VERSION)
    set(OpenCMISS_ParMETIS_VERSION "${OpenCMISS_ParMETIS_VERSION}" CACHE STRING "External ParMETIS library version number to use when building OpenCMISS libraries." FORCE)
  else()
    set(OpenCMISS_ParMETIS_VERSION "4.0.3" CACHE STRING "External ParMETIS library version number to use when building OpenCMISS libraries." FORCE)
  endif()
endif()
if(OpenCMISS_WITH_PETSc)
  if(DEFINED OpenCMISS_PETSc_VERSION)
    set(OpenCMISS_PETSc_VERSION "${OpenCMISS_PETSc_VERSION}" CACHE STRING "External PETSc library version number to use when building OpenCMISS libraries." FORCE)
  else()
    set(OpenCMISS_PETSc_VERSION "3.21.0" CACHE STRING "External PETSc library version number to use when building OpenCMISS libraries." FORCE)
  endif()
endif()
if(OpenCMISS_WITH_ScaLAPACK)
  if(DEFINED OpenCMISS_ScaLAPACK_VERSION)
    set(OpenCMISS_ScaLAPACK_VERSION "${OpenCMISS_ScaLAPACK_VERSION}" CACHE STRING "External ScaLAPACK library version number to use when building OpenCMISS libraries." FORCE)
  else()
    set(OpenCMISS_ScaLAPACK_VERSION "2.2.1" CACHE STRING "External SLEPc library version number to use when building OpenCMISS libraries." FORCE)
  endif()
endif()
if(OpenCMISS_WITH_SLEPc)
  if(DEFINED OpenCMISS_SLEPc_VERSION)
    set(OpenCMISS_SLEPc_VERSION "${OpenCMISS_SLEPc_VERSION}" CACHE STRING "External SLEPc library version number to use when building OpenCMISS libraries." FORCE)
  else()
    set(OpenCMISS_SLEPc_VERSION "3.21.0" CACHE STRING "External SLEPc library version number to use when building OpenCMISS libraries." FORCE)
  endif()
endif()
if(OpenCMISS_WITH_SUNDIALS)
  if(DEFINED OpenCMISS_SUNDIALS_VERSION)
    set(OpenCMISS_SUNDIALS_VERSION "${OpenCMISS_SUNDIALS_VERSION}" CACHE STRING "External SUNDIALS library version number to use when building OpenCMISS libraries." FORCE)
  else()
    set(OpenCMISS_SUNDIALS_VERSION "6.0.0" CACHE STRING "External SUNDIALS library version number to use when building OpenCMISS libraries." FORCE)
  endif()
endif()
