file(MAKE_DIRECTORY "${LibOpenCMISS_GEN_BINDINGS_PYTHON_SWIG_WRAPPER_DIR}")
swig_add_library(${LibOpenCMISS_PYTHON_MODULE}
  TYPE SHARED
  LANGUAGE Python
  OUTPUT_DIR ${LibOpenCMISS_GEN_BINDINGS_PYTHON_SWIG_WRAPPPER_DIR}
  SOURCES ${LibOpenCMISS_OPENCMISS_GENERATED_I}
)
set_property(TARGET ${LibOpenCMISS_PYTHON_MODULE} PROPERTY SWIG_INCLUDE_DIRECTORIES ${LibOpenCMISS_BINDINGS_PYTHON_SWIG_DIR})
set_property(TARGET ${LibOpenCMISS_PYTHON_MODULE} PROPERTY SWIG_COMPILE_OPTIONS ${LibOpenCMISS_PYTHONLIBS_SWIG_FLAGS})
list(APPEND LibOpenCMISS_CLEANUP_FILES "${LibOpenCMISS_OPENCMISS_PY}")
