cmake_path(SET _INC_DIRECTORY_PATH "${OpenCMISS_OPENCMISS_H}")
cmake_path(REMOVE_FILENAME _INC_DIRECTORY_PATH)
file(MAKE_DIRECTORY "${_INC_DIRECTORY_PATH}")
cmake_path(SET _SRC_DIRECTORY_PATH "${OpenCMISS_OPENCMISS_C_F90}")
cmake_path(REMOVE_FILENAME _SRC_DIRECTORY_PATH)
file(MAKE_DIRECTORY "${_SRC_DIRECTORY_PATH}")
execute_process(
  COMMAND "${OpenCMISS_Python_EXECUTABLE}" generate_bindings "${OpenCMISS_ROOT}" C "${OpenCMISS_OPENCMISS_H}" "${OpenCMISS_OPENCMISS_C_F90}"
  RESULT_VARIABLE OpenCMISS_Python_RESULT_VAR
  OUTPUT_VARIABLE OpenCMISS_Python_OUTPUT_VAR
  ERROR_VARIABLE OpenCMISS_Python_ERROR_VAR
  WORKING_DIRECTORY "${OpenCMISS_BINDINGS_DIR}"
)
if(NOT OpenCMISS_Python_RESULT_VAR EQUAL 0)
  message(STATUS "Generate C bindings failed.")
  message(STATUS "  Result: '${OpenCMISS_Python_RESULT_VAR}'")
  message(STATUS "  Output: '${OpenCMISS_Python_OUTPUT_VAR}'")
  message(STATUS "  Error: '${OpenCMISS_Python_ERROR_VAR}'")
endif()
