file(MAKE_DIRECTORY "${OpenCMISS_GEN_BINDINGS_Python_SWIG_WRAPPER_DIR}")
include(UseSWIG)
message(STATUS "OpenCMISS_Python_MODULE_TARGET = '${OpenCMISS_Python_MODULE_TARGET}'")
message(STATUS "OpenCMISS_GEN_BINDINGS_Python_SWIG_WRAPPER_DIR = '${OpenCMISS_GEN_BINDINGS_Python_SWIG_WRAPPER_DIR}'")
message(STATUS "OpenCMISS_OPENCMISS_GENERATED_I = '${OpenCMISS_OPENCMISS_GENERATED_I}'")
swig_add_library(${OpenCMISS_Python_MODULE_TARGET}
  TYPE SHARED
  LANGUAGE python
  OUTPUT_DIR ${OpenCMISS_GEN_BINDINGS_Python_SWIG_WRAPPER_DIR}
  SOURCES ${OpenCMISS_OPENCMISS_GENERATED_I}
)
#set_property(TARGET ${OpenCMISS_Python_MODULE_TARGET} PROPERTY SWIG_INCLUDE_DIRECTORIES ${OpenCMISS_BINDINGS_Python_SWIG_DIR})
#set_property(TARGET ${OpenCMISS_Python_MODULE_TARGET} PROPERTY SWIG_COMPILE_OPTIONS ${OpenCMISS_PYTHONLIBS_SWIG_FLAGS})
